name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
            - 1.85.0
        features:
            - "--features rusqlite"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
      - name: Test
        run: |
          cargo test --no-fail-fast ${{ matrix.features }}

  fmt-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: nightly
            components: clippy, rustfmt
      - name: Rust fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
